import {
  Avatar,
  Badge,
  Stack,
  Table,
  TableContainer,
  Tbody,
  Td,
  Tfoot,
  Th,
  Thead,
  Text,
  Tr,
  Center,
} from "@chakra-ui/react";
import { type NextPage } from "next";
import Head from "next/head";
import { CreateTicket } from "~/components/form/TicketForm";
import { LoadingProvider, LoadingSpinner } from "~/components/loading";
import { AssignModal, DeleteModal } from "~/components/modal";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.ticket.tickets.useQuery();
  console.log(data);
  if (isLoading)
    return (
      <LoadingProvider>
        <LoadingSpinner />
      </LoadingProvider>
    );
  if (!data) return <LoadingProvider>404</LoadingProvider>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container mx-auto p-4">
          <CreateTicket className="p-4 shadow-md " />
          {data.length == 0 ? (
            <Center>Nothing to Display!</Center>
          ) : (
            <TableContainer>
              <Table size="lg">
                <Thead>
                  <Tr>
                    <Th>Subject</Th>
                    <Th>Category</Th>
                    <Th>Status</Th>
                    <Th>Requestor</Th>
                    <Th>Assignee</Th>
                    <Th>Action</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  {data.map((ticket) => {
                    return (
                      <Tr key={ticket.id}>
                        <Td>{ticket.subject}</Td>
                        <Td>{ticket.category.replaceAll("_", " ")}</Td>
                        <Td>
                          <Badge
                            colorScheme={
                              ticket.status == "TBA"
                                ? "purple"
                                : ticket.status == "IN_PROGRESS"
                                ? "orange"
                                : ticket.status == "OPEN"
                                ? "cyan"
                                : "red"
                            }
                          >
                            {ticket.status}
                          </Badge>
                        </Td>
                        <Td>
                          <Stack direction={"row"} placeItems={"center"}>
                            <Avatar
                              size="md"
                              name={ticket.requestor.name ?? ""}
                              src={ticket.requestor.image ?? ""}
                            />

                            <Text as={"b"}>{ticket.requestor.name}</Text>
                          </Stack>
                        </Td>
                        <Td>
                          <Stack direction={"row"} placeItems={"center"}>
                            <Avatar
                              size="md"
                              name={ticket.assignee?.name ?? ""}
                              src={ticket.assignee?.image ?? ""}
                            />

                            <Text as={"b"}>
                              {ticket.assignee?.name ?? "Unassigned"}
                            </Text>
                          </Stack>
                        </Td>
                        <Td>
                          <Stack direction={"row"} placeItems={"center"}>
                            <AssignModal ticketId={ticket.id} />
                            <DeleteModal ticketId={ticket.id} />
                          </Stack>
                        </Td>
                      </Tr>
                    );
                  })}
                </Tbody>
                <Tfoot>
                  <Tr>
                    <Th>Subject</Th>
                    <Th>Category</Th>
                    <Th>Status</Th>
                    <Th>Requestor</Th>
                    <Th>Assignee</Th>
                    <Th>Action</Th>
                  </Tr>
                </Tfoot>
              </Table>
            </TableContainer>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
